// Authenticate
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGN_UP = 'SIGN_UP'
export const SET_LOGOUT_TIMER = 'SET_LOGOUT_TIMER'
export const SET_LOGIN_REQUEST = 'SET_LOGIN_REQUEST'
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS'
export const SET_LOGIN_FAILURE = 'SET_LOGIN_FAILURE'

// Users
export const GET_ME = 'GET_ME'
export const SET_USER_NAME = 'SET_USER_NAME'

// Courses
export const SET_COURSES = 'SET_COURSES'
export const SET_COURSE_DETAIL = 'SET_COURSE_DETAIL'

export const SET_CREATE_COURSE_REQUEST = 'SET_CREATE_COURSE_REQUEST'
export const SET_CREATE_COURSE_SUCCESS = 'SET_CREATE_COURSE_SUCCESS'
export const SET_CREATE_COURSE_FAILURE = 'SET_CREATE_COURSE_FAILURE'

export const SET_COURSE_LEARNED_REQUEST = 'SET_COURSE_LEARNED_REQUEST'
export const SET_COURSE_LEARNED_SUCCESS = 'SET_COURSE_LEARNED_SUCCESS'
export const SET_COURSE_LEARNED_FAILURE = 'SET_COURSE_LEARNED_FAILURE'

// DIRECTORY
export const SET_DIRECTORIES = 'SET_DIRECTORIES'
export const ADD_DIRECTORY = 'ADD_DIRECTORY'

// TOPICS
export const SET_TOPICS_REQUEST = 'SET_TOPICS_REQUEST'
export const SET_TOPICS_SUCCESS = 'SET_TOPICS_SUCCESS'
export const SET_TOPICS_FAILURE = 'SET_TOPICS_FAILURE'

export const SET_TOPIC_DETAIL_REQUEST = 'SET_TOPIC_DETAIL_REQUEST'
export const SET_TOPIC_DETAIL_SUCCESS = 'SET_TOPIC_DETAIL_SUCCESS'
export const SET_TOPIC_DETAIL_FAILURE = 'SET_TOPIC_DETAIL_FAILURE'

export const SET_TOPIC_LEARNED_REQUEST = 'SET_TOPIC_LEARNED_REQUEST'
export const SET_TOPIC_LEARNED_SUCCESS = 'SET_TOPIC_LEARNED_SUCCESS'
export const SET_TOPIC_LEARNED_FAILURE = 'SET_TOPIC_LEARNED_FAILURE'

export const SAVE_QUESTION_TOPIC = 'SAVE_QUESTION_TOPIC'
export const SAVE_ROOM_ID = 'SAVE_ROOM_ID'
export const SAVE_DATA_RANKING = 'SAVE_DATA_RANKING'
export const SAVE_ELAPSED_SECONDS = 'SAVE_ELAPSED_SECONDS'

// HISTORY
export const SET_HISTORIES_REQUEST = 'SET_HISTORIES_REQUEST'
export const SET_HISTORIES_SUCCESS = 'SET_HISTORIES_SUCCESS'
export const SET_HISTORIES_FAILURE = 'SET_HISTORIES_FAILURE'

// ALPHABET
export const SET_ALPHABET_REQUEST = 'SET_ALPHABET_REQUEST'
export const SET_ALPHABET_HIRAGANA_SUCCESS = 'SET_ALPHABET_HIRAGANA_SUCCESS'
export const SET_ALPHABET_KATAKANA_SUCCESS = 'SET_ALPHABET_KATAKANA_SUCCESS'
export const SET_ALPHABET_FAILURE = 'SET_ALPHABET_FAILURE'

// DISPLAY
export const OPEN_MENU = 'OPEN_MENU'
export const CLOSE_MENU = 'CLOSE_MENU'

export const OPEN_CARD = 'OPEN_CARD'
export const CLOSE_CARD = 'CLOSE_CARD'

export const OPEN_LOGIN = 'OPEN_LOGIN'
export const CLOSE_LOGIN = 'CLOSE_LOGIN'

export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'

