const imagesStudy = {
  background2: require('../../assets/background2.jpg'),
  background12: require('../../assets/background12.jpg'),
  backgroundBattle: require('../../assets/background-battle.jpg'),
  backgroundJapaneseGame: require('../../assets/background-language-japanese.jpeg'),
  backgroundJapaneseStudy: require('../../assets/background-japanese.jpeg'),
  avatar: require('../../assets/avatar.jpg'),
  logoReact: require('../../assets/logo-react.png'),
  logoEmail: require('../../assets/logo-email.png'),
  logoDocument: require('../../assets/logo-document.png'),
  logoLanguage: require('../../assets/logo-language.png'),
  logoKanji: require('../../assets/logo-kanji.png'),
  logoQuiz: require('../../assets/logo-quiz.jpeg'),
  iconEmail: require('../../assets/icon-email.png'),
  iconPassword: require('../../assets/icon-password.png'),
  iconEmailAnimated: require('../../assets/icon-email-animated.gif'),
  iconSunyata: require('../assets/Images/icons/icon-sunyata.png'),
  iconPasswordAnimated: require('../../assets/icon-password-animated.gif'),
  countDownStart: require('../assets/Images/countdown_start_alpha.gif'),
  logoDC: require('../../assets/logo-dc.png'),
  animationCheckDone: require('../../assets/lottie-checked-done'),
  animationCheckIncorrect: require('../../assets/incorrect'),
  animationLoadingFluid: require('../../assets/lottie-loading-fluid'),
  logoJapanese: require('../../assets/logo-japanese-kansa.png'),
  back: require('../../assets/back.png'),
  eyeGrey: require('../../assets/eye-grey.png'),
  eyeBlack: require('../../assets/eye-black.png'),
}

export default imagesStudy
